### ISSUE TITLE
Thoughts on adding icons from Paper after editing according to guidelines?

### ISSUE THREAD

**Issue by Anonymas** [materialos/Icons#104]

**Comment by crutchcorn** [comment]
Nope. Just nope. Remind me on Tuesday when I'm back home and I'll explain more

**Comment by HEXcube** [comment]
There's a license incompatibility. MaterialOS is [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/), while [Paper](https://github.com/snwh/paper-icon-theme/) is [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) (version isn't specified, so we're free to use any version :relaxed: ). CC BY-SA content can't be automatically converted to CC BY (though it's possible the other way around). So, unless Paper's creator Sam Hewitt contributes the icons himself or agrees to re-license his icons for MaterialOS, this can't be done.

**Comment by danielhickman** [comment]
Or we could sublicense the Paper icons with the same license that it's currently under.

**Comment by HEXcube** [comment]
Sublicense just for paper? :confused: U mean like those projects which combine works of different licenses, but mention each of 'em in a copyright or CREDITs file?

**Comment by danielhickman** [comment]
Yeah something like that if we are going to use Paper. It's our only option really.

**Comment by HEXcube** [comment]
Wonder why @crutchcorn says nope though! :confused:

**Comment by crutchcorn** [comment]
Back - sorry about that. While Mr.Hewitt has done an amazing job with Paper, I simply disagree with some of the icons' designs (not that I could do better). Not only that, but I would to not do this to limit what icons we are taking in (for a few reasons):
I don't want to take from sources other than what is contributed to us - that way we avoid issues and dependencies with other authors and things can look more consistent because they were designed FOR MOS.
